version: '2'

services:

  resizer:
    build: .
    links:
      - mysql
    encrypted_env_file: secret.env.encrypted
    command: sh test.sh

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'resizer'
