version: '2'

services:

  app:
    build:
      context: .
    environment:
      RESIZER_PROJECT_ID: syoya-tests
      RESIZER_BUCKET: resizer
      RESIZER_JSON: /secret/gcloud.json
      RESIZER_DB_USER: root
      RESIZER_DB_PROTOCOL: tcp
      RESIZER_DB_ADDRESS: mysql:3306
      RESIZER_DB_NAME: resizer
      # RESIZER_HOSTS: $RESIZER_HOSTS
    volumes:
      # - .:/go/src/github.com/go-microservices/resizer
      - ./secret:/secret
    depends_on:
      - mysql
    ports:
      - 80:3000

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'resizer'
